In [6]:
import pandas as pd

In [7]:
raw_csv_data = pd.read_csv('Absenteeism_data.csv')

In [9]:
raw_csv_data

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...
695,17,10,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,28,6,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,18,10,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,25,23,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,15,28,31/05/2018,291,31,40,237.656,25,1,1,1,2

In [10]:
df = raw_csv_data.copy()
df

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...
695,17,10,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,28,6,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,18,10,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,25,23,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,15,28,31/05/2018,291,31,40,237.656,25,1,1,1,2

In [11]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [14]:
df.head()

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         700 non-null    int64
 1   Reason for Absence         700 non-null    int64
 2   Date                       700 non-null    str
 3   Transportation Expense     700 non-null    int64
 4   Distance to Work           700 non-null    int64
 5   Age                        700 non-null    int64
 6   Daily Work Load Average    700 non-null    float64
 7   Body Mass Index            700 non-null    int64
 8   Education                  700 non-null    int64
 9   Children                   700 non-null    int64
 10  Pets                       700 non-null    int64
 11  Absenteeism Time in Hours  700 non-null    int64
dtypes: float64(1), int64(10), str(1)
memory usage: 72.6 KB

### Drop ID

In [18]:
df = df.drop(['ID'], axis = 1)

In [20]:
df.head()

,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,23,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [21]:
df['Reason for Absence']

0      26
1       0
2      23
3       7
4      23
5      23
6      22
7      23
8      19
9      22
10      1
11      1
12     11
13     11
14     23
15     14
16     23
17     21
18     11
19     23
20     10
21     11
22     13
23     28
24     18
25     25
26     23
27     28
28     18
29     23
30     18
31     18
32     23
33     18
34     23
35     23
36     24
37     11
38     28
39     23
40     23
41     23
42     23
43     19
44     23
45     23
46     23
47     23
48     22
49     14
50      0
51      0
52     23
53     23
54      0
55      0
56     18
57     23
58      0
59     23
60     23
61     23
62     23
63     23
64      0
65     23
66     23
67     23
68     23
69     23
70     23
71     23
72     23
73     23
74     19
75     14
76     28
77     26
78     23
79     28
80     23
81     23
82     13
83     21
84     23
85     10
86     22
87     14
88     23
89      6
90     23
91     21
92     13
93     28
94     28
95     28
96      7
97     23
98     23
99     19
100    23
101    26
102    23
103    26
104    19
105    22
106    28
107    28
108    23
109    22
110    27
111    19
112    23
113    23
114    19
115    27
116    18
117    27
118    23
119    28
120    27
121    27
122    27
123    27
124    27
125    27
126    27
127    27
128    27
129    18
130    18
131    27
132    23
133    27
134    27
135    23
136    22
137    23
138     1
139    11
140    28
141    23
142    28
143    22
144    11
145     1
146    28
147    23
148    23
149    23
150    25
151    18
152    23
153    23
154    19
155    28
156    19
157    19
158    17
159    22
160    13
161    13
162    14
163    13
164    11
165     1
166    26
167    13
168     6
169     8
170    28
171    23
172    14
173    13
174    23
175    11
176    13
177    11
178    11
179    13
180    14
181    28
182    14
183    28
184    28
185    23
186    28
187    13
188    23
189    28
190    28
191    13
192    23
193    23
194    14
195    28
196    28
197    19
198    19
199    12
200    19
201    13
202     7
203     0
204    13
205    28
206    28
207    18
208    19
209     7
210    28
211    12
212    13
213     0
214     0
215     0
216     0
217    11
218    13
219    22
220    19
221    22
222    10
223    23
224    10
225    11
226    23
227    10
228    13
229    13
230    23
231    13
232    22
233    11
234    28
235    28
236    19
237     1
238     5
239    26
240    26
241    18
242    25
243     1
244     1
245    25
246    22
247    26
248    26
249    19
250    19
251     0
252    19
253    19
254    23
255    18
256    13
257    14
258    28
259    23
260    23
261    11
262    23
263    13
264    25
265    23
266    23
267    19
268     8
269     6
270    11
271    23
272    19
273     0
274     9
275    28
276     0
277     0
278    13
279     9
280    23
281    28
282    28
283    26
284    28
285     0
286    28
287     7
288    13
289    24
290    26
291    26
292    22
293     0
294     0
295     1
296     7
297    22
298    28
299     1
300     0
301    19
302    28
303     0
304    23
305    23
306    28
307    28
308    23
309    28
310    10
311     0
312     0
313     0
314     1
315     7
316    23
317    11
318    23
319     6
320    28
321    23
322     1
323    11
324    26
325     0
326    18
327    11
328    25
329    28
330    13
331    12
332    13
333    28
334    10
335    15
336     0
337     0
338    23
339    12
340    28
341    28
342    23
343    28
344    28
345     4
346    28
347    28
348    23
349    25
350    25
351    28
352    13
353    14
354    26
355    28
356    28
357    19
358    23
359    19
360    23
361    13
362    23
363    26
364     3
365    26
366    26
367    28
368    28
369    28
370    27
371     7
372    22
373    28
374    23
375    27
376    27
377    10
378    26
379    27
380    22
381    27
382    23
383    23
384    11
385    27
386    27
387    10
388    27
389    27
390    18
391    19
392    28
393    28
394    28
395    22
396    22
397    22
398    28
399    22
400     0
401    21
402    23
403    14
404    13
405     0
406     0
407     0
408    28
409    22
410    19
411    28
412    28
413    28
414    26
415    22
416    26
417    23
418    28
419    23
420    13
421    28
422    28
423    28
424    11
425    13
426    23
427    10
428    23
429    28
430    23
431    28
432    11
433     8
434    18
435    25
436    13
437    25
438    28
439     1
440    23
441    23
442    28
443    28
444    23
445    28
446     0
447    13
448    28
449    28
450    28
451    26
452    28
453    23
454    23
455     5
456    21
457    28
458    11
459    13
460    23
461    25
462    13
463     7
464    25
465    26
466    26
467    28
468    15
469    23
470    28
471     9
472    28
473    23
474    22
475    22
476    26
477    28
478    28
479    23
480    25
481    25
482    28
483    28
484    26
485    26
486    28
487    25
488    25
489    23
490    23
491    28
492    28
493    28
494    28
495    28
496    28
497    28
498    23
499    28
500    23
501    23
502    23
503    23
504    23
505    23
506    22
507     4
508    11
509    26
510    14
511    28
512    23
513    23
514    23
515    23
516    23
517    23
518    23
519    26
520    28
521     1
522    23
523    10
524    13
525    10
526    10
527    23
528     6
529    10
530     0
531    13
532    21
533    28
534     2
535    28
536     9
537    24
538     1
539    23
540    22
541    28
542    13
543    14
544    28
545    23
546     8
547    23
548     0
549     0
550    14
551     0
552    23
553    26
554    28
555    13
556    28
557    23
558    13
559    23
560    23
561    14
562    18
563    26
564    18
565    13
566    23
567    23
568    23
569    18
570    12
571    12
572    25
573    25
574    13
575    25
576    10
577    18
578    27
579    18
580    27
581    27
582    13
583    27
584    27
585    13
586    23
587     1
588    27
589    28
590    27
591    27
592    28
593    27
594    19
595    27
596     7
597    27
598    27
599    25
600    13
601    23
602    27
603    12
604    27
605    27
606    13
607    27
608    25
609    25
610    27
611     7
612    27
613    23
614    25
615    27
616    27
617    25
618    27
619    23
620    25
621    25
622    12
623    27
624    27
625    27
626    25
627    27
628    25
629    19
630    13
631    27
632    27
633    27
634    10
635    13
636    27
637     7
638    27
639    23
640    25
641    27
642    23
643    27
644    23
645    27
646    27
647    23
648    13
649    27
650    27
651    13
652    19
653    22
654    13
655    10
656    19
657    19
658    13
659    27
660     7
661    16
662    23
663    23
664    10
665    22
666    27
667    19
668    16
669    27
670    28
671    19
672    14
673    27
674    22
675    19
676    28
677     8
678    26
679    13
680    28
681    14
682    19
683    22
684    27
685    23
686     5
687    28
688     0
689    27
690     0
691    16
692    10
693    10
694    22
695    10
696     6
697    10
698    23
699    28
Name: Reason for Absence, dtype: int64

In [23]:
df['Reason for Absence'].min()

np.int64(0)

In [25]:
df['Reason for Absence'].max()

np.int64(28)

In [27]:
pd.unique(df['Reason for Absence'])

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16])

In [28]:
len(df['Reason for Absence'].unique())

28

In [30]:
sorted(df['Reason for Absence'].unique())

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(15),
 np.int64(16),
 np.int64(17),
 np.int64(18),
 np.int64(19),
 np.int64(21),
 np.int64(22),
 np.int64(23),
 np.int64(24),
 np.int64(25),
 np.int64(26),
 np.int64(27),
 np.int64(28)]

### .get_dummies()

In [32]:
reason_columns = pd.get_dummies(df['Reason for Absence'])
reason_columns.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False

In [33]:
reason_columns['check'] = reason_columns.sum(axis = 1)
reason_columns.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28,check
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,1
1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,1
3,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,1

In [35]:
reason_columns.sum(axis = 0)

0         38
1         16
2          1
3          1
4          2
5          3
6          6
7         13
8          5
9          4
10        22
11        24
12         8
13        52
14        18
15         2
16         3
17         1
18        21
19        36
21         6
22        32
23       147
24         3
25        29
26        31
27        66
28       110
check    700
dtype: int64

In [36]:
reason_columns['check'].unique()

array([1])

In [ ]:
reason_columns = reason_columns.drop(['check'], axis = 1)

In [40]:
reason_columns.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False

In [41]:
reason_columns = pd.get_dummies(df['Reason for Absence'], drop_first=True)

In [42]:
reason_columns.head()

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False